# Generated by Django 6.0.3 on 2026-03-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address_customuser_date_of_hire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requires_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
