# Generated by Django 6.0.3 on 2026-03-19 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0007_route_geofence_radius_meters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_type', models.CharField(choices=[('Fill-up', 'Until Full'), ('Scheduled', 'Scheduled Time')], default='Fill-up', max_length=50)),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='Strict departure trigger if Scheduled', null=True)),
                ('ticket_color', models.CharField(default='Blue', help_text='e.g., Blue, Red, Yellow for passenger calling groups', max_length=50)),
                ('status', models.CharField(choices=[('Pending Vehicle', 'Waiting for Van'), ('Standing By', 'Standing By'), ('Loading', 'Calling Passengers'), ('Dispatched', 'Dispatched / In Transit'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending Vehicle', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet.route')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Can be unassigned if van is Arriving Soon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(blank=True, help_text='Optional Passenger Name', max_length=150)),
                ('seat_number', models.CharField(help_text='Assigned matrix seat', max_length=20)),
                ('fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Waiting', 'Waiting in Terminal'), ('Boarded', 'Boarded'), ('Cancelled', 'Cancelled / No Show')], default='Waiting', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.trip')),
            ],
        ),
    ]
