# Generated by Django 6.0.3 on 2026-03-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='traccar_device_id',
            field=models.CharField(blank=True, help_text="The unique identifier of this vehicle's GPS tracker device in Traccar", max_length=100, null=True, verbose_name='Traccar Device ID'),
        ),
    ]
