# Generated by Django 6.0.3 on 2026-03-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_add_traccar_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='is_master_hub',
            field=models.BooleanField(default=False, help_text='Grants global dispatch and viewing rights to personnel stationed here.'),
        ),
    ]
