# Generated by Django 6.0.3 on 2026-03-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_route_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='path_coordinates',
            field=models.JSONField(blank=True, default=list, help_text='Snap-to-road polyline coordinates generated by OSRM'),
        ),
        migrations.AddField(
            model_name='route',
            name='waypoints',
            field=models.JSONField(blank=True, default=list, help_text='List of lat/lng coordinates for terminal routing stops explicitly plotted'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, help_text='Total route distance in kilometers', max_digits=10),
        ),
        migrations.AlterField(
            model_name='route',
            name='est_travel_time',
            field=models.CharField(help_text="Estimated travel time, e.g., '1h 30m'", max_length=50),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delayed', 'Delayed')], default='Active', max_length=50),
        ),
    ]
