# Generated by Django 6.0.3 on 2026-03-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_route_path_coordinates_route_waypoints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='color',
            field=models.CharField(blank=True, default='#3b82f6', help_text='Hex color code for map rendering', max_length=20),
        ),
    ]
