# Generated by Django 6.0.3 on 2026-03-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0006_route_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='geofence_radius_meters',
            field=models.IntegerField(default=500, help_text='Meters around each terminal point to trigger arriving alerts'),
        ),
    ]
